require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FaturasController do

  # This should return the minimal set of attributes required to create a valid
  # Fatura. As you add validations to Fatura, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "cliente_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FaturasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all faturas as @faturas" do
      fatura = Fatura.create! valid_attributes
      get :index, {}, valid_session
      assigns(:faturas).should eq([fatura])
    end
  end

  describe "GET show" do
    it "assigns the requested fatura as @fatura" do
      fatura = Fatura.create! valid_attributes
      get :show, {:id => fatura.to_param}, valid_session
      assigns(:fatura).should eq(fatura)
    end
  end

  describe "GET new" do
    it "assigns a new fatura as @fatura" do
      get :new, {}, valid_session
      assigns(:fatura).should be_a_new(Fatura)
    end
  end

  describe "GET edit" do
    it "assigns the requested fatura as @fatura" do
      fatura = Fatura.create! valid_attributes
      get :edit, {:id => fatura.to_param}, valid_session
      assigns(:fatura).should eq(fatura)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fatura" do
        expect {
          post :create, {:fatura => valid_attributes}, valid_session
        }.to change(Fatura, :count).by(1)
      end

      it "assigns a newly created fatura as @fatura" do
        post :create, {:fatura => valid_attributes}, valid_session
        assigns(:fatura).should be_a(Fatura)
        assigns(:fatura).should be_persisted
      end

      it "redirects to the created fatura" do
        post :create, {:fatura => valid_attributes}, valid_session
        response.should redirect_to(Fatura.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fatura as @fatura" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fatura.any_instance.stub(:save).and_return(false)
        post :create, {:fatura => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:fatura).should be_a_new(Fatura)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fatura.any_instance.stub(:save).and_return(false)
        post :create, {:fatura => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fatura" do
        fatura = Fatura.create! valid_attributes
        # Assuming there are no other faturas in the database, this
        # specifies that the Fatura created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fatura.any_instance.should_receive(:update_attributes).with({ "cliente_id" => "1" })
        put :update, {:id => fatura.to_param, :fatura => { "cliente_id" => "1" }}, valid_session
      end

      it "assigns the requested fatura as @fatura" do
        fatura = Fatura.create! valid_attributes
        put :update, {:id => fatura.to_param, :fatura => valid_attributes}, valid_session
        assigns(:fatura).should eq(fatura)
      end

      it "redirects to the fatura" do
        fatura = Fatura.create! valid_attributes
        put :update, {:id => fatura.to_param, :fatura => valid_attributes}, valid_session
        response.should redirect_to(fatura)
      end
    end

    describe "with invalid params" do
      it "assigns the fatura as @fatura" do
        fatura = Fatura.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fatura.any_instance.stub(:save).and_return(false)
        put :update, {:id => fatura.to_param, :fatura => { "cliente_id" => "invalid value" }}, valid_session
        assigns(:fatura).should eq(fatura)
      end

      it "re-renders the 'edit' template" do
        fatura = Fatura.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fatura.any_instance.stub(:save).and_return(false)
        put :update, {:id => fatura.to_param, :fatura => { "cliente_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fatura" do
      fatura = Fatura.create! valid_attributes
      expect {
        delete :destroy, {:id => fatura.to_param}, valid_session
      }.to change(Fatura, :count).by(-1)
    end

    it "redirects to the faturas list" do
      fatura = Fatura.create! valid_attributes
      delete :destroy, {:id => fatura.to_param}, valid_session
      response.should redirect_to(faturas_url)
    end
  end

end
